#pragma once

#define RGBLIGHT_LIMIT_VAL 145
#define RGBLIGHT_HUE_STEP  4
#define RGBLIGHT_SAT_STEP  10
#define RGBLIGHT_VAL_STEP  8

#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 145
#define RGB_MATRIX_HUE_STEP  4
#define RGB_MATRIX_SAT_STEP  10
#define RGB_MATRIX_VAL_STEP  8

#define USE_SERIAL
